[package]
name = "leveldb"
version = "0.0.1"
authors = [ "adumbidiot <nathaniel.daniel23@outlook.com>" ]
edition = "2018"
license = "MIT"

[dependencies]
leveldb-sys = { path = "lib/leveldb-sys" }

[workspace]
members = [ "lib/leveldb-sys" ]
